"use client";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import { Toaster } from "react-hot-toast";
import Navbar from "./components/Navbar";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import { RootStyleRegistry } from './components/RootStyleRegistry'
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const headersList = usePathname();
  console.log(
    "🚀 ~ file: layout.js:15 ~ RootLayout ~ headersList:",
    headersList
  );
  const specificRoute = "admin"; // exclude specific router

  return (
    <html lang="en">
      <body>
        {!headersList.includes(specificRoute) && <Navbar />}
        <RootStyleRegistry>
          {children}
        </RootStyleRegistry>
        <Toaster />
      </body>
    </html>
  );
}
